name: Deploy
on:
  push:
    branches:
      - deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Update unenv
        run: pnpm update unenv
      # Keeping only *globals* because importing nodejs modules simply does not work in jstz.
      - name: Truncate data
        run: |
          mkdir /tmp/data
          for f in $(ls ./data); do cat ./data/$f | jq '."*globals*" | del(."*self*")' > /tmp/data/$f; done
          rm ./data/*.json && mv /tmp/data/*.json ./data
          pnpm run generate:table
      - name: Build
        run: cd report && pnpm run build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: report/build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
